name: Build OS Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '11 17 * * 0'
  workflow_dispatch:

permissions:
  contents: read    # To checkout the repository
  packages: write   # To push container images to GHCR

jobs:
  prepare-build:
    name: Prepare Build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prep.outputs.matrix }}
    steps:
      - name: Generate Matrix Configuration
        id: prep
        env:
          HOST_CONFIG: |
            {
              "dogwood": {},
              "elm": {},
              "plum": {},
              "tan": {}
            }
        run: |
          IMAGE_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME_LOWER=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          matrix=$(jq -n --argjson config "$HOST_CONFIG" \
                          --arg owner "$IMAGE_OWNER_LOWER" \
                          --arg repo "$REPO_NAME_LOWER" \
                          --arg sha "${{ github.sha }}" \
                          '{"include": [
                             $config | to_entries[] | {
                               host: .key,
                               tags: "ghcr.io/\($owner)/\($repo)-\(.key):latest,ghcr.io/\($owner)/\($repo)-\(.key):\($sha)",
                               platform: (.value.platform // "linux/amd64"),
                             }
                           ]}')

          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo "$matrix" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build-base-image:
    name: Build Base Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Build Container Image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./Containerfile
          target: headless
          platforms: linux/amd64, linux/amd64/v2
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-publish-image:
    name: Build and Publish Host Images
    runs-on: ubuntu-latest
    needs: [build-base-image, prepare-build]
    strategy:
      matrix: ${{ fromJSON(needs.prepare-build.outputs.matrix) }}
    steps:
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Build and push Docker image for ${{ matrix.host }}
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./Containerfile
          target: ${{ matrix.host }}
          platforms: ${{ matrix.platform }}
          provenance: false
          push: true
          tags: ${{ matrix.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
